# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9eaaf893a715272995f9881d43856d8e7644703b047233fad8c7d969e31c00ca2da2e014155f3f6a86a095edf20d008bff26b5648a25931d94cdc9a3b7ff3bda

test:
  secret_key_base: 35a5f0cd9b891368d81de056f2addc04898686cd197938390f3f9695f61d62aef073f6039b3edd36791b9cf23b24e356e959d100b40a09480d255a4ac19af910

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
